name: bird_chat
description: BirdChat application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  gherkin: ^1.1.5
  flutter_gherkin: ^1.1.5
  intl: ^0.16.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.5
  http: ^0.12.0+2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/mock.json
    - assets/loading.gif
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto/Roboto-Regular.ttf

    

